### ISSUE TITLE
Device is already producing framedata

### ISSUE THREAD

**Issue by celticsamurai** [ChrisAJS/lgx2userspace#16]
I actually already know how to get around this, but I'm just wondering if there are any plans in the future to make it so that we don't have to unplug and replug our capture card?

**Comment by ChrisAJS** [comment]
I hate it too. 

The unfortunate thing is the devices are incredibly chatty and when analysing literally thousands of requests during device initialisation, I couldn't isolate any kind of command structure that I could then interrogate and figure out.

I assume the drivers, or RECcentral detect when a full frame hasn't been received and then sends some kind of message/messages to the device which will then cause the device to do whatever happens when you unplug and replug the hdmi.

Due to the large number of messages being sent and the split second nature of video frames, it really makes figuring out the protocol difficult.

I'll definitely put it on the list of things to do, but right now it feels insurmountable.

**Comment by celticsamurai** [comment]
Dang. Oh well. I've also been trying to find commands to reset USB devices
without necessarily unplugging them. Do you know of a a good one, by any
chance?

**Comment by ChrisAJS** [comment]
Libusb does have a reset function but I think the gc550 & gc551 don't acknowledge it (?) At least the bootstrapping process is persisted even after the call.

**Comment by celticsamurai** [comment]
Well couldn't hurt to try it. What's the name of the command?

**Comment by ChrisAJS** [comment]
I did give it a go but it's [libusb_device_reset](https://nxmnpg.lemoda.net/3/libusb_reset_device)

**Comment by celticsamurai** [comment]
Well dang. It was worth a shot anyway. Thanks!

**Comment by Nama** [comment]
This issue should be open.
